name: DeathLogger
version: '${project.version}'
main: cc.synkdev.deathlogger.DeathLogger
api-version: '1.13'
authors: [ Synk ]
depend:
  - NexusCore
softdepend:
  - SkinsRestorer
permissions:
  deathlogger.teleport.all:
    description: Teleport to any death's location
    default: op
  deathlogger.teleport.self:
    description: Teleport to your own deaths' locations
    default: op
  deathlogger.coordinates.all:
    description: Teleport to any death's location
    default: op
  deathlogger.coordinates.self:
    description: Teleport to your own deaths' locations
    default: op
  deathlogger.inventory.view.all:
    description: View the inventory from any death
    default: op
  deathlogger.inventory.view.self:
    description: View the inventory from your own deaths
    default: op
  deathlogger.inventory.take:
    description: Give yourself the inventory from deaths
    default: op
  deathlogger.inventory.give:
    description: Give the players the inventory from their deaths
    default: op
  deathlogger.players:
    description: View the players menu
    default: true
  deathlogger.player:
    description: View the player (specific player's deaths) menu
    default: true
  deathlogger.reload:
    description: Reload the plugin
    default: op
  deathlogger.lastdeath.self:
    description: View the time since your last death
    default: true
  deathlogger.lastdeath.all:
    description: View the time since a player's last death
    default: true
  deathlogger.respawn.self:
    description: View the location of your last respawn
    default: true
  deathlogger.respawn.all:
    description: View the location of a player's last respawn
    default: op
  deathlogger.respawn.teleport.all:
    description: Teleport to any player's respawn location
    default: op
  deathlogger.respawn.teleport.self:
    description: Teleport to your own respawn locations
    default: op
  deathlogger.respawn.coordinates.all:
    description: View the coordinates of any player's respawn location
    default: op
  deathlogger.respawn.coordinates.self:
    description: View the coordinates of your own deaths' respawn locations
    default: op